arch:
# - amd64
 - arm64
# - ppc64el
language: generic

env:
- BUILD=1
- BUILD=2
- BUILD=3
- BUILD=4
- BUILD=5
- BUILD=6
- BUILD=7
- BUILD=8
- BUILD=9
- BUILD=10
- BUILD=11
- BUILD=12
- BUILD=13
- BUILD=14
- BUILD=15
- BUILD=16
- BUILD=17
- BUILD=18
- BUILD=19
- BUILD=20
- BUILD=21
- BUILD=22
- BUILD=23
- BUILD=24

install: skip

script:
# Environment information
- echo "==> Environment information"
- uname -a
- grep ^processor /proc/cpuinfo
- free -m
- df -h

# Snaps
- echo "==> Snaps"
- sudo snap install core || true
- sudo snap install core
- sudo snap install hello-world
- hello-world

# Docker
- echo "==> Docker"
- sudo docker info
- sudo docker run hello-world
